exports.quaryList={
    GET_STORE_LIST_QUARY:"SELECT STORE_ID, STORE_NAME, STORE_ADDRESS, STORE_CODE, FROM BMS.STORE",
    SAVE_STORE_QUARY:"INSERT INTO BMS.STORE (STORE_NAME, STORE_ADDRESS, STORE_CODE, CREATED_ON, CREATED_BY) VALUES(? ,? ,?, ?, ?)"
}